# Form implementation generated from reading ui file 'h:\Проекты\Для лабы\HandsTracker\qtforms\CameraWidget\CameraWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CameraWidget(object):
    def setupUi(self, CameraWidget):
        CameraWidget.setObjectName("CameraWidget")
        CameraWidget.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CameraWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=CameraWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_image = QtWidgets.QWidget()
        self.page_image.setObjectName("page_image")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_image)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.video_widget = QVideoWidget(parent=self.page_image)
        self.video_widget.setObjectName("video_widget")
        self.verticalLayout_3.addWidget(self.video_widget)
        self.stackedWidget.addWidget(self.page_image)
        self.page_video = QtWidgets.QWidget()
        self.page_video.setObjectName("page_video")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_video)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_label = QtWidgets.QLabel(parent=self.page_video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setStyleSheet("background-image: url(\"./no-camera.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_2.addWidget(self.image_label)
        self.stackedWidget.addWidget(self.page_video)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(CameraWidget)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CameraWidget)

    def retranslateUi(self, CameraWidget):
        _translate = QtCore.QCoreApplication.translate
        CameraWidget.setWindowTitle(_translate("CameraWidget", "Form"))
        self.image_label.setText(_translate("CameraWidget", "TextLabel"))
from PyQt6.QtMultimediaWidgets import QVideoWidget
